# Generated by Django 2.2.7 on 2019-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermercado', models.CharField(max_length=12)),
                ('sku', models.CharField(max_length=12)),
                ('articulo', models.CharField(max_length=50)),
                ('precio', models.CharField(default=0, max_length=20)),
                ('url_img', models.CharField(max_length=200)),
                ('oferta', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
