# Generated by Django 2.2.7 on 2019-11-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='articulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='sku',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='supermercado',
            field=models.CharField(max_length=20),
        ),
    ]
